
{'date': 'Mon Jun 27 2022 17:42:07.343 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 30
    Aventura().main()
AttributeError: 'Aventura' object has no attribute 'main'
'''},
{'date': 'Mon Jun 27 2022 17:42:53.297 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 32
    print(ADV[:100])
NameError: name 'ADV' is not defined
'''},
{'date': 'Mon Jun 27 2022 17:59:45.694 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 332
    Aventura().main(ADV)
  module <module> line 28
    i = "\n".join( ini for kind, ini in self.roteiro if kind == "I")
ValueError: need more than 1 value to unpack
'''},
{'date': 'Mon Jun 27 2022 18:14:27.910 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 34
  if kind == "L"
                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jun 27 2022 18:14:39.743 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 340
    Aventura().main(ADV)
  module <module> line 36
    locais[umlocal] = [cmd]
IndexError: list assignment index out of range
'''},
{'date': 'Mon Jun 27 2022 18:16:27.618 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 341
    Aventura().main(ADV)
  module <module> line 38
    locais[umlocal].append(cmd)
IndexError: list index out of range
'''},
{'date': 'Mon Jun 27 2022 18:38:23.831 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 344
    Aventura().main(ADV)
  module <module> line 34
    print([lc[o] for lc in locais])
NameError: name 'o' is not defined
'''},
{'date': 'Mon Jun 27 2022 21:52:25.84 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 20
  _, cmd = adv[0]]
                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jun 27 2022 21:52:36.135 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 21
  loc, desc = cmd.split(":)
                           ^
SyntaxError: EOL while scanning string literal
'''},
{'date': 'Mon Jun 27 2022 21:52:47.975 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 352
    Aventura().main(ADV)
  module <module> line 40
    locais = [Cenario(rot[ini:fim]) for ini,fim in zip(lro, lro[1:]+[len(rot)])]
  module <module> line 22
    Cenario.CENA[loc] = self
AttributeError: 'Cenario' object has no attribute 'CENA'
'''},
{'date': 'Mon Jun 27 2022 21:53:15.267 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 352
    Aventura().main(ADV)
  module <module> line 42
    print([lc[0] for lc in locais])
AttributeError: 'Cenario' object has no attribute '__getitem__'
'''},
{'date': 'Mon Jun 27 2022 22:12:23.274 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 362
    Aventura().main(ADV)
  module <module> line 49
    locais = [Cenario(rot[ini:fim]) for ini,fim in zip(lro, lro[1:]+[len(rot)])]
  module <module> line 26
    self.objeto = [Objeto(rot[ini:fim]) for ini,fim in zip(lro, lro[1:]+[len(adv)])]
  module <module> line 35
    loc, self.descreve = cmd.split(":")
ValueError: need more than 1 value to unpack
'''},
{'date': 'Mon Jun 27 2022 23:05:33.903 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 384
    Aventura().main(ADV)
  module <module> line 71
    locais = [Cenario(rot[ini:fim]) for ini,fim in zip(lro, lro[1:]+[len(rot)])]
  module <module> line 28
    self.objeto = [Objeto(adv[ini:fim],self) for ini,fim in zip(lro, lro[1:]+[len(adv)])]
  module <module> line 41
    self.verbo = {adv[ini].split(":")[-2]:Verbo(adv[ini:fim], cenario) for ini,fim in zip(lro, lro[1:]+[len(adv)])}
AttributeError: 'list' object has no attribute 'split'
'''},
{'date': 'Mon Jun 27 2022 23:14:09.27 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 43
  self.verbo = {(verbo:=Verbo(adv[ini:fim], cenario)).dercreve:verbo
                        ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jun 27 2022 23:14:36.945 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 43
  self.verbo = {(verbo:=Verbo(adv[ini:fim], cenario)).descreve:verbo
                        ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jun 27 2022 23:17:00.936 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''[VOCE ESTA NA COZINHA DA VOVO AQUI VOCE VAI PREPARAR A SALADA, VOCE ESTA NA SALA DE JANTAR. COM UMA MESA E MOVEIS DE VIME, O SAGUAO DA VOVO E GRANDE, OS ARCOS LEVAM A SALA DE JANTAR E A  ESCADA AO SEGUNDO ANDAR, ESTE E O TERRENO DA TIA LOURDES, VOCE SE EQUILIBRA NO MURO ETA MURO ALTO SO! MELHOR EU ME  AGARRAR EM ALGUMA COISA!  PARECE FIRME PARA SE AGARRAR  E TEM UM MAMAO AMARELINHO NELE, VOCE ESTA NA ORLA DA PISCINA, VOCE ESTA EM FRENTE DA CASA DO SEU ZE, O CASEIRO, VOCE ESTA NA RAMPA QUE LEVA DO PATIO ATE A PISCINA, NO PATIO HA UMA JAQUEIRA,A CASA DA VO E BEM EM FRENTE, UMA RAMPA  LEVA 'A PISCINA 'A DIREITA, VOCE ESTA NA RUA SAPHIRO ARAUJO,A NO SITIO DA VOVO..., VOCE ESTA EM SEU APARTAMENTO NA CIDADE, LOUCA PARA IR AO SITIO]
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 389
    Aventura().main(ADV)
  module <module> line 79
    print(Cenario.OBJ)
  module <module> line 46
    return f"@{self.descreve} <{list(self.verbo.keys())}>"
  module <module> line 1
    (list(self.verbo.keys()))
AttributeError: 'list' object has no attribute 'keys'
'''},
{'date': 'Tue Jun 28 2022 09:43:02.164 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 386
    Aventura().main(ADV)
  module <module> line 81
    locais.pop().vai()
  module <module> line 31
    texto = self.descreve + "\nVocê pode ver" + "\n".join(ob for ob in self.objeto)
TypeError: sequence item 0: expected str instance, Objeto found
'''},
{'date': 'Tue Jun 28 2022 09:43:02.829 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 386
    Aventura().main(ADV)
  module <module> line 81
    locais.pop().vai()
  module <module> line 31
    texto = self.descreve + "\nVocê pode ver" + "\n".join(ob for ob in self.objeto)
TypeError: sequence item 0: expected str instance, Objeto found
'''},
{'date': 'Tue Jun 28 2022 10:00:55.24 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 391
    Aventura().main(ADV)
TypeError: __init__() missing 2 positional arguments: adv,cenario
'''},
{'date': 'Tue Jun 28 2022 10:13:43.463 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 393
    Aventura().main(ADV)
  module <module> line 88
    locais.pop().vai()
  module <module> line 33
    texto = self.descreve + "\nVocê pode ver:\n" + "\n".join(ob.mostra() for ob in self.objeto.keys())
AttributeError: 'str' object has no attribute 'mostra'
'''},
{'date': 'Tue Jun 28 2022 10:27:46.999 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 400
    Aventura().main(ADV)
  module <module> line 95
    locais.pop().vai()
  module <module> line 35
    self.interpreta(fala+ ["", ""])
  module <module> line 42
    self.objeto[substantivo].vai(verbo) if substantivo in self.objeto else self.nop(fala)
NameError: name 'substantivo' is not defined
'''},
{'date': 'Tue Jun 28 2022 11:24:43.710 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 42
  verbo, substantivo = [termo[:5] for termo in fala[:2]
                                                                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Jun 28 2022 11:29:34.246 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 408
    Aventura().main(ADV)
  module <module> line 103
    locais.pop().vai()
  module <module> line 36
    self.interpreta(fala+ ["", ""])
  module <module> line 43
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 63
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 79
    verbo, substantivo = [termo[:5] for termo in fala[:2]]
AttributeError: 'Objeto' object has no attribute '__getitem__'
'''},
{'date': 'Tue Jun 28 2022 11:43:22.681 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 74
  acoes = dict(M=lambda loc: lambda:move(loc), M=lambda loc: lambda:move(loc))
                                                ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Tue Jun 28 2022 11:43:22.816 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 74
  acoes = dict(M=lambda loc: lambda:move(loc), M=lambda loc: lambda:move(loc))
                                                ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Tue Jun 28 2022 11:43:57.109 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 408
    Aventura().main(ADV)
  module <module> line 103
    locais.pop().vai()
  module <module> line 36
    self.interpreta(fala+ ["", ""])
  module <module> line 43
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 63
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 79
    verbo, substantivo = self.verbo, self.decreve or fala.descreve
AttributeError: 'Verbo' object has no attribute 'decreve'
'''},
{'date': 'Tue Jun 28 2022 12:24:33.709 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 418
    Aventura().main(ADV)
  module <module> line 112
    locais = [Cenario(rot[ini:fim], self) for ini,fim in zip(lro, lro[1:]+[len(rot)])]
  module <module> line 29
    self.obj = [Objeto(adv[ini:fim],self) for ini,fim in zip(lro, lro[1:]+[len(adv)])]
  module <module> line 58
    verbos = [Verbo(adv[ini:fim], cenario).itens()
  module <module> line 82
    self.acao = [acoes[kind](suplement) for kind, suplement in adv[::-1]]
NameError: name 'move' is not defined
'''},
{'date': 'Wed Jun 29 2022 09:05:29.71 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 418
    Aventura().main(ADV)
  module <module> line 113
    locais.pop().vai()
  module <module> line 36
    self.interpreta(fala+ ["", ""])
  module <module> line 43
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 63
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 86
    [action() for action in self.acao]
  module <module> line 73
    return go(arg)
  module <module> line 95
    input(f"Pegando: {descreve}\nObjeto {Cenario.OBJ[self.nome].descricao} guardado")
  module <module> line 1
    (Cenario.OBJ[self.nome].descricao)
AttributeError: 'Verbo' object has no attribute 'nome'
'''},
{'date': 'Wed Jun 29 2022 09:06:14.764 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 418
    Aventura().main(ADV)
  module <module> line 113
    locais.pop().vai()
  module <module> line 36
    self.interpreta(fala+ ["", ""])
  module <module> line 43
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 63
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 86
    [action() for action in self.acao]
  module <module> line 73
    return go(arg)
  module <module> line 95
    input(f"Pegando: {descreve}\nObjeto {Cenario.OBJ[substantivo].descricao} guardado")
  module <module> line 1
    (Cenario.OBJ[substantivo].descricao)
AttributeError: 'Objeto' object has no attribute 'descricao'
'''},
{'date': 'Wed Jun 29 2022 09:55:19.435 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 428
    Aventura().main(ADV)
  module <module> line 123
    locais.pop().vai()
  module <module> line 36
    self.interpreta(fala)
  module <module> line 47
    raise "sai"
TypeError: exceptions must derive from BaseException
'''},
{'date': 'Wed Jun 29 2022 10:08:31.636 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 434
    Aventura().main(ADV)
  module <module> line 127
    locais = [Cenario(rot[ini:fim], self) for ini,fim in zip(lro, lro[1:]+[len(rot)])]
  module <module> line 30
    self.obj = [Objeto(adv[ini:fim],self) for ini,fim in zip(lro, lro[1:]+[len(adv)])]
  module <module> line 68
    verbos = [Verbo(adv[ini:fim], cenario).itens()
  module <module> line 93
    self.cenario.interpreta(input(lro)) if lro else None
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
AttributeError: 'Cenario' object has no attribute 'objeto'
'''},
{'date': 'Wed Jun 29 2022 10:11:48.998 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 437
    Aventura().main(ADV)
  module <module> line 130
    locais = [Cenario(rot[ini:fim], self) for ini,fim in zip(lro, lro[1:]+[len(rot)])]
  module <module> line 30
    self.obj = [Objeto(adv[ini:fim],self) for ini,fim in zip(lro, lro[1:]+[len(adv)])]
  module <module> line 68
    verbos = [Verbo(adv[ini:fim], cenario).itens()
  module <module> line 93
    self.cenario.interpreta(input(lro)) if lro else None
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
AttributeError: 'Cenario' object has no attribute 'objeto'
'''},
{'date': 'Wed Jun 29 2022 10:22:14.928 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 93
  [del adv[ix] for ix,(kind,cmd) in enumerate(adv[::-1]) if kind == "B"]
                ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Jun 29 2022 10:22:15.72 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 93
  [del adv[ix] for ix,(kind,cmd) in enumerate(adv[::-1]) if kind == "B"]
                ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Jun 29 2022 10:23:52.817 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 2
  # SPDX-License-Identifier: GPL-3.0-or-later
                                           ^
SyntaxError: can't delete expr
'''},
{'date': 'Wed Jun 29 2022 10:30:25.659 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 439
    Aventura().main(ADV)
  module <module> line 134
    locais.pop().vai()
  module <module> line 37
    self.interpreta(fala)
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 73
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 102
    self.cenario.interpreta(input(f"vb:{self.descreve}")) if self.descreve else None
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 73
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 42
    self.interpreta(input(texto)) if not self.exit else None
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 73
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 42
    self.interpreta(input(texto)) if not self.exit else None
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 73
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 103
    [action() for action in self.acao]
  module <module> line 83
    return go(arg)
  module <module> line 110
    local.vai()
AttributeError: 'str' object has no attribute 'vai'
'''},
{'date': 'Wed Jun 29 2022 10:53:50.684 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 452
    Aventura().main(ADV)
  module <module> line 146
    locais.pop().vai()
  module <module> line 37
    self.interpreta(fala)
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 74
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 110
    [action() for action in self.acao]
TypeError: prep() got an unexpected keyword argument 'ativa'
'''},
{'date': 'Wed Jun 29 2022 10:55:46.486 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 452
    Aventura().main(ADV)
  module <module> line 146
    locais.pop().vai()
  module <module> line 37
    self.interpreta(fala)
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 74
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 42
    self.interpreta(input(texto)) if not self.exit else None
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 74
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 110
    [action() for action in self.acao]
  module <module> line 88
    return go(arg, **kwarg)
  module <module> line 127
    self.cenario.interpreta(input(f"Pegando: {descreve}\nObjeto {Cenario.OBJ[substantivo].descreve} guardado"))
  module <module> line 51
    self.vai()
  module <module> line 37
    self.interpreta(fala)
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 74
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 109
    self.cenario.interpreta(input(f"vb:{self.descreve}")) if self.descreve else None
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 74
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 110
    [action() for action in self.acao]
  module <module> line 88
    return go(arg, **kwarg)
  module <module> line 120
    self.cenario.interpreta(input(lro)) if lro else None
  module <module> line 51
    self.vai()
  module <module> line 37
    self.interpreta(fala)
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 74
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 110
    [action() for action in self.acao]
  module <module> line 88
    return go(arg, **kwarg)
  module <module> line 118
    local.ativa() if ativa else local.deastiva()
AttributeError: 'Objeto' object has no attribute 'deastiva'
'''},
{'date': 'Wed Jun 29 2022 11:03:57.112 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 453
    Aventura().main(ADV)
  module <module> line 145
    locais = [Cenario(rot[ini:fim], self) for ini,fim in zip(lro, lro[1:]+[len(rot)])]
  module <module> line 30
    self.obj = [Objeto(adv[ini:fim],self) for ini,fim in zip(lro, lro[1:]+[len(adv)])]
  module <module> line 69
    verbos = [Verbo(adv[ini:fim], cenario).itens()
TypeError: itens() missing 1 positional argument: it
'''},
{'date': 'Wed Jun 29 2022 11:04:58.614 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 133
  def noper(self):
  ^
IndentationError: expected an indented block
'''},
{'date': 'Wed Jun 29 2022 11:06:33.643 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 455
    Aventura().main(ADV)
  module <module> line 149
    locais.pop().vai()
  module <module> line 37
    self.interpreta(fala)
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 74
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 110
    [action() for action in self.acao]
  module <module> line 88
    return go(arg, **kwarg)
TypeError: noper() takes 1 positional arguments but more were given
'''},
{'date': 'Wed Jun 29 2022 11:15:45.313 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 456
    Aventura().main(ADV)
  module <module> line 150
    locais.pop().vai()
  module <module> line 37
    self.interpreta(fala)
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 74
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 110
    [action() for action in self.acao]
  module <module> line 88
    return go(arg, **kwarg)
  module <module> line 122
    self.cenario.interpreta(input(lro)) if lro else None
  module <module> line 51
    self.vai()
  module <module> line 37
    self.interpreta(fala)
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 74
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 110
    [action() for action in self.acao]
  module <module> line 88
    return go(arg, **kwarg)
  module <module> line 122
    self.cenario.interpreta(input(lro)) if lro else None
  module <module> line 51
    self.vai()
  module <module> line 37
    self.interpreta(fala)
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 74
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 110
    [action() for action in self.acao]
  module <module> line 88
    return go(arg, **kwarg)
  module <module> line 115
    Cenario.OBJ[obj].descreve = descreve
NameError: name 'obj' is not defined
'''},
{'date': 'Wed Jun 29 2022 11:53:14.257 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 3
  """ Engenho de aventuras textuais.
             ^
SyntaxError: can't delete expr
'''},
{'date': 'Wed Jun 29 2022 11:53:47.208 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 103
  (del adv[ix]) if foi else adv[ix] = ["B", self.lro]
               ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Jun 29 2022 11:55:41.622 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 463
    Aventura().main(ADV)
  module <module> line 157
    locais.pop().vai()
  module <module> line 37
    self.interpreta(fala)
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 74
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 116
    [action() for action in self.acao]
  module <module> line 88
    return go(arg, **kwarg)
  module <module> line 125
    local = Cenario.OBJ[objeto]
KeyError: CIBELE, FUI COMPRAR REVISTINHAS
 VOLTO JA, SE VOCE QUISER ALGO,
 PECA AO SEU PAI ASS
'''},
{'date': 'Wed Jun 29 2022 11:58:00.852 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 464
    Aventura().main(ADV)
  module <module> line 156
    locais = [Cenario(rot[ini:fim], self) for ini,fim in zip(lro, lro[1:]+[len(rot)])]
  module <module> line 30
    self.obj = [Objeto(adv[ini:fim],self) for ini,fim in zip(lro, lro[1:]+[len(adv)])]
  module <module> line 69
    verbos = [Verbo(adv[ini:fim], cenario).itens()
  module <module> line 106
    obj, descreve = cmd.split(":")
ValueError: need more than 1 value to unpack
'''},
{'date': 'Wed Jun 29 2022 11:59:21.297 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 464
    Aventura().main(ADV)
  module <module> line 156
    locais = [Cenario(rot[ini:fim], self) for ini,fim in zip(lro, lro[1:]+[len(rot)])]
  module <module> line 30
    self.obj = [Objeto(adv[ini:fim],self) for ini,fim in zip(lro, lro[1:]+[len(adv)])]
  module <module> line 69
    verbos = [Verbo(adv[ini:fim], cenario).itens()
  module <module> line 106
    obj, descreve, *_ = cmd.split(":")
ValueError: need more than 1 value to unpack
'''},
{'date': 'Wed Jun 29 2022 12:00:20.210 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 464
    Aventura().main(ADV)
  module <module> line 158
    locais.pop().vai()
  module <module> line 37
    self.interpreta(fala)
  module <module> line 53
    self.objeto[substantivo].vai(fala) if substantivo in self.objeto else self.nop(fala)
  module <module> line 74
    self.verbo[verbo].vai(self) if verbo in self.verbo else self.cenario.nop(fala, self.nome)
  module <module> line 117
    [action() for action in self.acao]
  module <module> line 88
    return go(arg, **kwarg)
  module <module> line 125
    objeto, descreve = local.split(":")
ValueError: too many values to unpack (expected 2)
'''},
{'date': 'Wed Jun 29 2022 12:03:13.431 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
RuntimeError: too much recursion
  module '$exec_1456' line 41
        texto = f"{obj}: Não deu certo essa de '{verbo} {substantivo}'" if fala else "Repete, não entendi"
'''},
{'date': 'Wed Jun 29 2022 12:04:16.930 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
RuntimeError: too much recursion
  module '$exec_320' line 41
        texto = f"{obj}: Não deu certo essa de '{verbo} {substantivo}'" if fala else "Repete, não entendi"
'''},
{'date': 'Wed Jun 29 2022 16:50:42.3 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 109
  M=lambda loc: prep(self.move,loc), Z=lambda loc: prep(self.mostra,loc,ativa = False))
   ^
SyntaxError: keyword argument repeated
'''},